import React, { useState } from "react";
import "../components/faq.css"

const faqs = [
    {
        question: "How can I generate AI images for free using ChatGPT?",
        answer: "You can generate AI images for free by using ChatGPT with built-in image generation tools. Just enter a descriptive prompt, and it will generate a unique image based on your input."
    },
    {
        question: "What is a good image prompt example for ChatGPT?",
        answer: 'A good image prompt is specific and detailed. For example: "A futuristic cityscape at dusk with neon lights and flying cars, in cyberpunk style."'
    },
    {
        question: "Can I use ChatGPT image prompts without coding skills?",
        answer: "Yes! Just type your image idea in plain English. No coding knowledge is required."
    },
    {
        question: "Are the AI images generated by ChatGPT free to use?",
        answer: "Yes, images generated with ChatGPT are generally free to use for personal and non-commercial purposes. Always check OpenAI’s latest terms of use."
    },
    {
        question: "How do I write better image prompts for ChatGPT?",
        answer: "Be descriptive. Include elements like scene, style, lighting, and mood. The more details, the better the image results."
    }
];

const FaqSection = () => {
    const [activeIndex, setActiveIndex] = useState(null);

    const toggleFAQ = (index) => {
        setActiveIndex(index === activeIndex ? null : index);
    };

    return (
        <section className="faq-section">
            <h2 className="faq-title">Frequently Asked Questions</h2>
            <div className="faq-container">
                {faqs.map((faq, index) => (
                    <div
                        className={`faq-item ${activeIndex === index ? "active" : ""}`}
                        key={index}
                    >
                        <button
                            className="faq-question"
                            onClick={() => toggleFAQ(index)}
                            aria-expanded={activeIndex === index}
                        >
                            {faq.question}
                            <span className="faq-toggle-icon">
                                {activeIndex === index ? "−" : "+"}
                            </span>
                        </button>
                        <div
                            className="faq-answer"
                            style={{ display: activeIndex === index ? "block" : "none" }}
                        >
                            <p>{faq.answer}</p>
                        </div>
                    </div>
                ))}
            </div>
        </section>
    );
};

export default FaqSection;
